name: translate_dictionary_builder
description: "Build runner package to generate translate dictionary"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  build: ^4.0.2
  flutter:
    sdk: flutter

  glob: ^2.1.3
  source_gen: ^4.0.1
  yaml: ^3.1.3

  flutter_translate:
    git:
      url: https://github.com/carlosalito/flutter_translate.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: