name: translate_dictionary_builder
description: "Build runner package to generate translate dictionary"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.3
  source_gen: ^2.0.0
  build: ^2.4.2

  flutter_translate:
    git:
      url: https://github.com/carlosalito/flutter_translate.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: